const button ="added a button";
consolr.log(button);
const login ="login page added";
console.log("login");
const footer="fotter added also";
console.log(footer);
const upi="intregate upi also";
console.log(upi);
const gitpush="2nd time push";
console.log(gitpush);